import HEX from "./Colors/HEX";
import RGBA from "./Colors/RGBA";
import Particle from "./Particle";
import ParticleSystemOptions from "./Options/ParticleSystemOptions";
import { VectorInterval, Shape, Interval, ParticleCreateCallback } from "..";
import Plugin from "./Plugin";
export default class ParticleSystem {
    private readonly canvas;
    private canvasSize;
    private lastId;
    particles: Map<string, Particle>;
    private _ctx;
    private animationFrameId;
    private lastUpdate;
    private plugins;
    private updateMethods;
    private createMethods;
    pluginData: Map<string, Record<string, any>>;
    amount: number;
    life: Interval;
    size: Interval;
    velocity: VectorInterval;
    acceleration: VectorInterval;
    colors: (RGBA | HEX)[];
    opacity: Interval;
    shapes: Shape[];
    static numberInRange(interval: Interval): number;
    private static elementFromArray;
    installPlugin(plugin: Plugin): void;
    private createParticle;
    init(): void;
    private update;
    stop(): void;
    clear(): void;
    onParticleCreate(callback: ParticleCreateCallback): ParticleCreateCallback;
    constructor(canvas: HTMLCanvasElement, options: ParticleSystemOptions);
}
